### ISSUE TITLE
error on auto_commit=False

### ISSUE THREAD

**Issue by Dorianux** [datastore/datastore-git#1]
When I init a GitDatastore with auto_commit=False,
and after some ds.put(..) then finally 
ds.commit("message", author="Test"):

the commit is done, but no commit-info is commited.
the commit misses: author, date and commit message.

Do i do it right? 
Or is this a bug?

Cool project - by the way!

**Comment by jbenet** [comment]
Hey @Dorianux, seems like it's a bug, as that should work. Are you using the git command-line or dulwich?

**Comment by Dorianux** [comment]
wow - you are fast!
I am using dulwich
